<?php
if (!defined('ABSPATH')) exit;

/**
 * 初始化 RSS 设置
 */
function paper_wp_rss_init() {
    if (!is_feed()) return;

    // 设置 header
    header('Content-Type: application/rss+xml; charset=UTF-8', true);
    
    // 禁用 emoji 转换
    remove_filter('the_content_feed', 'wp_staticize_emoji');
    remove_filter('the_excerpt_rss', 'wp_staticize_emoji');
    remove_filter('comment_text_rss', 'wp_staticize_emoji');
    
    // 禁用 wpautop，防止自动添加 P 标签导致嵌套错误
    remove_filter('the_content_feed', 'wpautop');
    remove_filter('the_excerpt_rss', 'wpautop');
    
    // 禁用缓存
    add_filter('wp_feed_cache_transient_lifetime', '__return_zero');
}
add_action('template_redirect', 'paper_wp_rss_init', 1);

/**
 * RSS 内容清洗 - 移除无关的 UI 元素，保留核心内容
 */
function paper_wp_rss_content_cleanup($content) {
    if (!is_feed()) return $content;

    // 0. 预处理：手动添加必要的段落（如果禁用了 wpautop 导致纯文本没有标签）
    // 如果内容没有以 <p, <h, <div, <ul, <ol, <pre, <blockquote 开头，可能需要处理
    // 但通常编辑器内容已有标签，这里主要处理 wpautop 留下的后遗症或原始嵌套

    // 1. 移除特定的 UI 组件
    $patterns_to_remove = [
        '/<div[^>]*class="[^"]*(?:ai-summary|ai-summary-block|hidden|no-feed|copy-code-btn)[^"]*"[^>]*>.*?<\/div>/is',
        '/<button[^>]*>.*?<\/button>/is',
        '/<script[^>]*>.*?<\/script>/is',
        '/<style[^>]*>.*?<\/style>/is',
        '/\s*style="[^"]*"/i',
        '/\s*class="[^"]*"/i',
        '/\s*id="[^"]*"/i',
    ];
    
    $content = preg_replace($patterns_to_remove, '', $content);

    // 2. 移除通用的 div 标签 (Unwrap)
    $content = preg_replace('/<[\/]?div[^>]*>/i', '', $content);

    // 3. 修复 P 标签嵌套问题 (这是导致 "Unexpected end tag" 的常见原因)
    // 将 <p>...<p>... 转换为 <p>...</p><p>...
    // 简单策略：如果发现 <p> 内部包含块级元素，尝试修复
    
    // 移除空标签
    $content = preg_replace('/<p>\s*<\/p>/i', '', $content);
    
    // 确保没有 orphan </p> (孤立的结束标签)
    // 这是一个简单的清理，防止验证错误
    // $content = preg_replace('/<\/p>\s*(?!<)/i', "</p>\n", $content); // 仅增加换行
    
    return trim($content);
}
add_filter('the_content_feed', 'paper_wp_rss_content_cleanup', 10);

/**
 * 添加特色图片到 RSS 内容顶部
 */
function paper_wp_rss_add_featured_image($content) {
    if (!is_feed()) return $content;
    
    global $post;
    
    if (has_post_thumbnail($post->ID)) {
        $image_id = get_post_thumbnail_id($post->ID);
        $image_url = wp_get_attachment_image_src($image_id, 'large');
        
        if ($image_url) {
            $img_html = '<p><img src="' . esc_url($image_url[0]) . '" width="' . esc_attr($image_url[1]) . '" height="' . esc_attr($image_url[2]) . '" alt="' . esc_attr(get_the_title()) . '" style="display: block; margin-bottom: 20px; max-width: 100%;" /></p>';
            $content = $img_html . $content;
        }
    }
    
    return $content;
}
add_filter('the_content_feed', 'paper_wp_rss_add_featured_image', 5);
add_filter('the_excerpt_rss', 'paper_wp_rss_add_featured_image', 5);


/**
 * RSS 版权信息和原文链接
 */
function paper_wp_rss_footer($content) {
    if (!is_feed()) return $content;
    
    global $post;
    
    if (!is_single($post->ID)) return $content; // 确保是文章

    $link = get_permalink($post->ID);
    $title = get_bloginfo('name');
    
    $footer = '<hr />';
    $footer .= '<p>原文链接：<a href="' . esc_url($link) . '">' . get_the_title() . '</a></p>';
    $footer .= '<p>&copy; ' . date('Y') . ' <a href="' . home_url() . '">' . $title . '</a>. All rights reserved.</p>';
    
    return $content . $footer;
}
add_filter('the_content_feed', 'paper_wp_rss_footer', 20);


/**
 * 添加 RSS 命名空间支持 (Media, Content, DC)
 */
function paper_wp_add_rss_namespace() {
    echo 'xmlns:content="http://purl.org/rss/1.0/modules/content/"' . "\n";
    echo 'xmlns:dc="http://purl.org/dc/elements/1.1/"' . "\n";
    echo 'xmlns:media="http://search.yahoo.com/mrss/"' . "\n";
    echo 'xmlns:atom="http://www.w3.org/2005/Atom"' . "\n";
}
add_action('rss2_ns', 'paper_wp_add_rss_namespace');

/**
 * 在 RSS item 中添加 <media:content> 标签 (帮助 Feedly 等抓取封面)
 */
function paper_wp_rss_add_media_tag() {
    global $post;
    if (has_post_thumbnail($post->ID)) {
        $image_id = get_post_thumbnail_id($post->ID);
        $image_url = wp_get_attachment_image_src($image_id, 'large'); // 使用大图
        $mime_type = get_post_mime_type($image_id);
        
        if ($image_url) {
            echo '<media:content url="' . esc_url($image_url[0]) . '" medium="image" width="' . esc_attr($image_url[1]) . '" height="' . esc_attr($image_url[2]) . '" type="' . esc_attr($mime_type) . '" />';
        }
    }
}
add_action('rss2_item', 'paper_wp_rss_add_media_tag');

/**
 * 调试信息 (仅在 WP_DEBUG 开启时显示)
 */
function paper_wp_rss_debug_info($content) {
    if (is_feed() && defined('WP_DEBUG') && WP_DEBUG) {
        $content .= "\n<!-- RSS Generated by BarePaper Theme | Time: " . date('Y-m-d H:i:s') . " -->";
    }
    return $content;
}
add_filter('the_content_feed', 'paper_wp_rss_debug_info', 99);
